### ISSUE TITLE
Components nested more than 2 levels deep don't get started

### ISSUE THREAD

**Issue by cap10morgan** [donut-party/system#24]
Steps to reproduce:

```clojure
(-> {::ds/defs {:env {:port #::ds{:start (constantly 1234)}}}} ds/start ::ds/instances)
;; => {:env {:port 1234}}

;; now add :http key to nest :port component 3 levels deep...
(-> {::ds/defs {:env {:http {:port #::ds{:start (constantly 1234)}}}}} ds/start ::ds/instances)
;; => {:env {:http {:port #:donut.system{:start #object[clojure.core$constantly$fn__5740
                                                  0x9a06bf2
                                                  "clojure.core$constantly$fn__5740@9a06bf2"]}}}}
```

Expected: Both instances would have their `:port` components started and resolved to `1234`.

Observed: When the `:port` component is nested >2 levels deep, its start fn is not called and shows up in the instance.

**Comment by flyingmachine** [comment]
Thanks for this! The organization of component definitions into a 2-level structure of `{:component-group {:component ...}}` is a deeply embedded design decision and isn't going to change, sadly.

Also, not sure how true the repro steps are to your usage, but in this particular case it would work to have

```clojure
{::ds/defs {:env {:port 1234}}}
```

[Constant instances](https://github.com/donut-party/system#constant-instances) for more info

If you'd like more thoughts on config-ing the system so that `:env` is organized the way you'd like, just let me know :)

**Comment by cap10morgan** [comment]
> Thanks for this! The organization of component definitions into a 2-level structure of `{:component-group {:component ...}}` is a deeply embedded design decision and isn't going to change, sadly.

OK I'll just reorganize everything into that structure then. And maybe see if this can be called out more directly in the docs (though it's possible it is already and I just missed it).

> 
> 
> 
> Also, not sure how true the repro steps are to your usage, but in this particular case it would work to have
> 
> 
> 
> ```clojure
> 
> {::ds/defs {:env {:port 1234}}}
> 
> ```
> 
> 
> 
> [Constant instances](https://github.com/donut-party/system#constant-instances) for more info

Yeah that was just to keep the example simple. The place I actually ran into this needs a start fn.

> 
> 
> 
> If you'd like more thoughts on config-ing the system so that `:env` is organized the way you'd like, just let me know :) 

Thanks! In the meantime, I think this issue can be closed.
