### ISSUE TITLE
New feature request: maps of like-components

### ISSUE THREAD

**Issue by kjothen** [donut-party/system#9]
Firstly, thanks for the library! Being data-driven makes it very powerful indeed, and I use it everywhere.
My usage is quite straightforward I think: an edn file where the system is defined and a multi-method builder that builds it, eg

```
;; system.edn
{:donut.system/defs
  {:group-1 
    {:component-a "foo" 
     :component-b "bar" 
     :dependent-component-x {:d [:donut.system/ref [:group-1 :component-a]]}
     :dependent-component-y {:d [:donut.system/ref [:group-1 :component-b]]}
}}}
```
```
;; system.clj
(defmulti component (fn [k _] k))
(defmethod component :default [_ v] v)
(defmethod component :component-a [_ v] (build-component v))
(defmethod component :component-b [_ v] (build-component v))
,,,
```

In essence, dispatching on the `group` and `component` names. However, many times the components aren't unique concepts, they could be two connections to the same type of resource, such as a database. It's inconvenient to give these new components unique names in the edn file, because I then have to change my dispatch code too, which prevents my system from being data-driven, eg `component-b` above is just another instance of whatever is returned by `build-component`, and I already have the code to build these.

I was thinking whether you may consider introducing the concept of a map of like-components? My definition might look something like this, and it would just require a new-style `ref` keyword (and associated processing)I think:

```
{:donut.system/defs
  {:group-1
    {:components {:a "foo" :b "bar"}
     :dependent-components {:x {:d [:donut.system/key-ref [:group-1 :components :a]]}
                            :y {:d [:donut.system/key-ref [:group-1 :components :b]]}
```

and then my builder code becomes something like this instead, and I never have to touch it again no matter how many like-components I build:

```
;; system.clj
(defmulti component (fn [k _] k))
(defmethod component :default [_ v] v)
(defmethod component :components [_ v] (map  (fn [[k' v']] (assoc k' (build-component v')) v)))
,,,
```
I think this feature, or something very similar, is actually mentioned as a TODO in the documentation under the heading [Creating multiple instances of groups of components](https://github.com/donut-party/system#creating-multiple-instances-of-groups-of-components)

**Comment by flyingmachine** [comment]
Hey! Thanks for the kind words :)

I'm not sure I'm understanding the context correctly. Is this right?

* You have a system defined in an edn file. We'll call this `raw-system-map`
* In system.clj you read the system.edn file, and then do some processing to produce a system map. We'll call this `processed-system-map`
* The processing involves updating component component keys in `raw-system-map` with the return value from a multimethod, `component`. `component` takes two arguments, the component name (`k`) and the raw component definition (`v`)
* The `defmethod` for some of your components is identical - in your example, both `:component-a` and `:component-b` have the body `(build-component v)`
* If you want to add additional components to `raw-system-map` which are processed in the same way as existing components, you have to add more `defmethods` for the new components

If that's the case, then I think there are a few different ways to address your issue, which I outline below. By the way, which version of donut.system are you using? If you're using an older version than some of the code below might be a little confusing. I've changed the way component definitions work a little bit since I first released the library.

## Use donut.system's "deep refs"

This isn't well-documented, but the functionality you're wanting with `:donut.system/key-ref` already exists. You could have a raw system map that looked like this:

```clojure
{:donut.system/defs
 {:group-1
  {:database-connections
   {:donut.system/config {:names [:a :b]}}

   :dependent-component-a
   {:donut.system/config {:db [:donut.system/ref [:group-1 :database-connections :a]]}}

   :dependent-component-b
   {:donut.system/config {:db [:donut.system/ref [:group-1 :database-connections :b]]}}}}}
```

Here, the refs "reach in" to another component. The ref `[:group-1 :database-connections :a]` assumes that the `:database-connections` component is going to be a map with the key `:a`. However, the system definition as-is won't support this assumption. In your system.clj you'd have to have something like this:

```clojure
(assoc-in system
          [:group-1 :database-connections :donut.system/start]
          (fn [component-def]
            (let [connection-names (get-in component-def [:donut.system/config :names])]
              (->> connection-names
                   (map (fn [connection-name]
                          [connection-name (get-connection connection-name)]))
                   (into {})))))
```

This is defining the `[:group-1 :database-connections]` start behavior to produce a map using all of the connection names you defined in the component's `:donut.system/config` key. 

## Change pre-processing

After reading the raw system map from `system.edn` you could include a step that looks for all key names that have some kind of pattern, like `:database-connection-X`, and handle the component-building for those keys separately.

## Group components differently

Finally, you could organize your component definitions differently such that you have two groups:

```clojure
{:group-1
 {:database-connection {}
  :component-a         {}}

 :group-2
 {:database-connection {}
  :component-b         {}}}
```

This way, if your `component` multimethod dispatches on component name (as it appears to) then you can have the same component name in different groups.

---

Would any of these work?

**Comment by kjothen** [comment]
Thanks for your full and detailed response - that's very considerate of you!

The first option works for me. I hadn't appreciated there was support for deep references, and it was very simple to make this work in the end by doing exactly as you suggest, eg create a start function for `datasources` which unwraps its `config` for any dependent `datasource`.

```clojure
; system.edn
{:system
 {:db
  {...
   :datasources
   {:a {:port [:donut.system/ref [:db :container-mapped-exposed-port]]
        :user "test"
        :password "test"
        :dbtype "postgres"}}
   :datasource [:donut.system/ref [:db :datasources :a]]}}}
```

```clojure
; components.clj
...
(def datasources
  {:donut.system/start (fn [{:donut.system/keys [config]}] config)
   :donut.system/config donut.system/required-component})

(def datasource
  {:donut.system/start (fn [{:donut.system/keys [config]}]
                           (next.jdbc/get-datasource config))
   :donut.system/config donut.system/required-component})
```

```clojure
; system.clj
(defmulti component (fn [k _] k))
(defmethod component :default [_ v] v)
...
(defn merge-component-config
  [component config]
  (update component :donut.system/config (fn [original] (deep-merge original config))))
...
(defmethod component :datasources [_ v]
  (merge-component-config
   components/datasources v))

(defmethod component :datasource [_ v]
  (merge-component-config
    components/datasource v))
```
I had considered dealing with this in pre-processing, and that would work of course, but I didn't want to deviate too far from the supported capability in case the library changes in the future.

As for the group components differently option, I didn't really like it for aesthetic reasons mainly, as my group tends to represent a major infrastructure resource (pubsub, db, http-server, etc) and I'd rather not have lots of tiny top-level groups such as: pubsub-client, pubsub-connection, pubsub-topics, etc.

Thanks again for your steer - I hoped there would be an elegant solution, and overlooked a data-driven approach in plain sight all along.
